EntityFrameworkProject/Models/Social.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Models
{
    public class Social : BaseEntity
    {
        [Required(ErrorMessage = "Name can't be empty")]
        [StringLength(20, ErrorMessage = "The size of text max 20")]
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

EntityFrameworkProject/Areas/AdminArea/Controllers/SocialController.cs
using EntityFrameworkProject.Data;
using EntityFrameworkProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class SocialController : Controller
    {

        private readonly AppDbContext _context;

        public SocialController(AppDbContext context)
        {
            _context = context;
        }
        // GET: SocialController
        public async Task<IActionResult> Index()
        {
            List<Social> socials = await _context.Socials.Where(m => !m.IsDeleted).AsNoTracking().OrderByDescending(m => m.Id).ToListAsync();
            return View(socials);
        }

        // GET: SocialController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return BadRequest();

            Social social = await _context.Socials.FindAsync(id);

            if (social == null) return NotFound();

            return View(social);
        }

        // GET: SocialController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: SocialController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Social social)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View();
                }

                bool isExist = await _context.Socials.AnyAsync(m => m.Name.Trim() == social.Name.Trim() && m.Url.Trim() == social.Url.Trim());
                if (isExist)
                {
                    ModelState.AddModelError("Name And Url", "Category already exist");
                    return View();
                }

                await _context.Socials.AddAsync(social);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: SocialController/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                Social social = await _context.Socials.FirstOrDefaultAsync(m => m.Id == id);

                if (social is null) return NotFound();

                return View(social);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // POST: SocialController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Social social)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(social);
                }

                Social dbSocial = await _context.Socials.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbSocial is null) return NotFound();

                if (dbSocial.Name.ToLower().Trim() == social.Name.ToLower().Trim() && dbSocial.Url.ToLower().Trim() == social.Url.ToLower().Trim())
                {
                    return RedirectToAction(nameof(Index));
                }

                //dbCategory.Name = category.Name;

                _context.Socials.Update(social);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

       

        // POST: SocialController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Social social = await _context.Socials.FirstOrDefaultAsync(m => m.Id == id);

            social.IsDeleted = true;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

EntityFrameworkProject/Areas/AdminArea/Views/Social/Create.cshtml
@model Social

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            Category
                        </p>
                        <form asp-controller="Social" asp-action="Create" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Name</label>
                                <input maxlength="" minlength="" type="text" class="form-control" asp-for="Name">
                                <span class="text-danger my-1" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername2">Url</label>
                                <input  type="text" class="form-control" asp-for="Url">
                                <span class="text-danger my-1" asp-validation-for="Url"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-controller="Social" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
}

EntityFrameworkProject/Areas/AdminArea/Views/Social/Details.cshtml
@model Social

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            Social detail
        </div>
        <div class="card-body">
            <p class="card-text">@Model.Name</p>
            <p class="card-text">@Model.Url</p>
        </div>
    </div>
</div>

EntityFrameworkProject/Areas/AdminArea/Views/Social/Edit.cshtml
@model Social

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            Social
                        </p>
                        <form asp-controller="Social" asp-action="Edit" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Name</label>
                                <input maxlength="" minlength="" type="text" class="form-control" asp-for="Name">
                                <span class="text-danger my-1" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername2">Name</label>
                                <input  type="text" class="form-control" asp-for="Url">
                                <span class="text-danger my-1" asp-validation-for="Url"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-controller="Social" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{

    <partial name="_ValidationPartial" />
}

EntityFrameworkProject/Areas/AdminArea/Views/Social/Index.cshtml
@model List<Social>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid my-3 mx-3">
    <div class="table-responsive pt-3">
        <div class="create-btn mb-3">
            <a asp-controller="Social" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th style="text-align: center;">
                        URL
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Social social in Model)
                {
                <tr>
                    <td>
                        @social.Name
                    </td>
                    <td>
                        @social.Url
                    </td>
                    <td style="text-align: center;">
                        <a asp-action="Details" asp-route-id="@social.Id" class="btn btn-info"><i class="mdi mdi-information mx-0"></i></a>
                        <a asp-action="Edit" asp-route-id="@social.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                        <form style="display: inline-block;" asp-action="Delete" asp-route-id="@social.Id" method="post">
                            <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                        </form>
                    </td>
                </tr>
                }


            </tbody>
        </table>
    </div>
</div>